<?php
/** @var Webgriffe_Multiwarehouse_Block_Adminhtml_Qty $this */
$_enabled = $this->getIsEnabled();
?>
<div id="wgmulti_qty_container">
    <input type="hidden" name="wgmulti_original_use_multiple_qty" value="<?php echo $_enabled ? '1' : '0' ?>">

    <input type="checkbox" name="wgmulti_use_multiple_qty" id="wgmulti_use_multiple_qty" value="1" <?php echo $_enabled ? 'checked="checked"' : '' ?>>
    <label class="normal" for="wgmulti_use_multiple_qty"><?php echo $this->__('Use multiple quantities') ?></label>

    <table id = "warehouse_qty_table" style="display:none;" class="data border">
        <tr>
            <th><?php echo $this->__('Code') ?></th>
            <th><?php echo $this->__('Name') ?></th>
            <th><?php echo $this->__('Qty') ?></th>
        </tr>
    <?php foreach ($this->getWarehouses() as $_id => $_data): ?>
        <tr>
            <td><?php echo $_data['code']?></td>
            <td><?php echo $_data['name']?></td>
            <td><input type="text" value="<?php echo $_data['qty']?>" name="wgmultiqty[<?php echo $_id ?>]" style="width: 50px"/></td>
        </tr>
    <?php endforeach ?>
    </table>
</div>
<script type="text/javascript">

    document.observe("dom:loaded", function() {
        var elem = $$('#table_cataloginventory tr')[1].select('td')[1];

        elem.insert(
            document.getElementById('wgmulti_qty_container')
        );

        $('wgmulti_use_multiple_qty').observe('change', function() {
            if ($F('wgmulti_use_multiple_qty')) {
                $('warehouse_qty_table').show();
                $('inventory_qty').disable();
            } else {
                $('warehouse_qty_table').hide();
                $('inventory_qty').enable();
            }
        });

        if ($F('wgmulti_use_multiple_qty')) {
            $('warehouse_qty_table').show();
            $('inventory_qty').disable();
        } else {
            $('warehouse_qty_table').hide();
            $('inventory_qty').enable();
        }

    });


</script>
